"""Data loaders for Project 06. Infrastructure only: no inference happens here.

All loaded data describes a fictional, synthetic educational simulation.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Dict, List

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

SYNTHETIC_DATA_NOTICE = (
    "All sequences, sensor observations, and hidden states in this project are synthetic "
    "educational data generated by a Hidden Markov Model simulator. This is NOT a real "
    "traffic feed or a real queueing system."
)

NOISE_LEVEL_FILES = {
    0.05: "sequence_len200_noise05_seed42.csv",
    0.15: "sequence_len200_noise15_seed42.csv",
    0.30: "sequence_len200_noise30_seed42.csv",
}


def load_hmm_config(path: Path = DATA_DIR / "hmm_config.json") -> dict:
    """Load hidden states, observation symbols, initial distribution, and matrices."""
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def load_scenarios(path: Path = DATA_DIR / "scenarios.json") -> List[dict]:
    """Load the named demo scenarios (stable low, rapid transition, high-noise, misleading)."""
    with path.open("r", encoding="utf-8") as handle:
        raw = json.load(handle)
    return raw["scenarios"]


def load_sequence(noise_level: float, data_dir: Path = DATA_DIR) -> List[Dict[str, object]]:
    """Load a committed (hidden_state, observation) sequence for one of the three noise levels."""
    filename = NOISE_LEVEL_FILES.get(round(noise_level, 2))
    if filename is None:
        raise ValueError(
            f"No committed sequence for noise_level={noise_level}; choose one of {sorted(NOISE_LEVEL_FILES)}"
        )
    path = data_dir / filename
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        row["step"] = int(row["step"])
    return rows
